data_directory_on_host: "../../data"

voc:
  data_directory: "/data/VOC2012"
  train_set_path: "ImageSets/Segmentation/train.txt"
  validation_set_path: "ImageSets/Segmentation/val.txt"

hariharan:
  data_directory: "/data/hariharan_semantic_contours_dataset"
  train_set_path: "dataset/train_noval.txt"
  validation_set_path: "dataset/val.txt"

batch_size: 4
