data_directory_on_host: "../../data"

voc_data_images_directory: "/data/VOC2012/JPEGImages"
voc_data_segmentations_directory: "/data/VOC2012/SegmentationClass"
voc_training_samples_list_path: "/data/VOC2012/ImageSets/Segmentation/train.txt"
voc_validation_samples_list_path: "/data/VOC2012/ImageSets/Segmentation/val.txt"

harikaran_data_images_directory: "/data/hariharan_semantic_contours_dataset/dataset/img"

batch_size: 4

# Dimension to which images will be padded during training, so that images of different original size
# can be batched together
training_image_dimension: 512
