name: Default workflow
on: [push]

jobs:
  run_commit_stage:
    runs-on: ubuntu-20.04
    # container:
    #   image: tensorflow/tensorflow:2.2.0-gpu
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          apt update && apt install -y wget vim git
          pip install -r requirements.txt
      - name: check git
        run: which git && git --version
      - name: check directory content
        run: ls -la
      - name: run commit stage
        run: invoke tests.commit-stage
