name: Default workflow
on: [push]

jobs:
  run_commit_stage:
    runs-on: ubuntu-20.04
    container: tensorflow/tensorflow:2.2.0-gpu
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: pip install ./requirements.txt

